### ISSUE TITLE
Build Actions & CI

### ISSUE THREAD

**Issue by patteki** [AntMeNet/AntMeClassic#13]
Maybe ask @TheBlubb14 for his help and or a similar implementation like in [OctoPatch](AusLiebeZumCode/OctoPatch)!?

**Comment by tomwendel** [comment]
Das ist vermutlich nicht ganz so einfach, da wir noch das klassische Framework am Start haben. So weit ich das gesehen habe funktionieren die Build Actions erst mal nur mit Core

**Comment by tomwendel** [comment]
Was schreib ich da?! Natürlich geht das :D
