### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by tomwendel** [AntMeNet/AntMeClassic#19]
Update installer by

- make sure versions are set automatically (CI)
- Include the right files
- Doublecheck requirements for plain installations (.NET Version, DirectX, VC++ Redists (FNA),...)

**Comment by patteki** [comment]
hab mal angefangen, mit dem Installer, aber es fehlt noch einiges, aber Wix ist schon echt geil xD
https://github.com/AntMeNet/AntMeClassic/commit/18c1d4d9ec39d66b927aaecfdfaf521bed5e3412

**Comment by tomwendel** [comment]
Bitte erst die Doku lesen 🙃 es gibt viel zu beachten - gerade beim Thema Upgrade. Und bitte nicht einfach XNA ersetzen sondern ein neues Feature erstellen und im Upgrade Pfad berücksichtigen

**Comment by patteki** [comment]
> Bitte erst die Doku lesen 🙃 es gibt viel zu beachten - gerade beim Thema Upgrade. Und bitte nicht einfach XNA ersetzen sondern ein neues Feature erstellen und im Upgrade Pfad berücksichtigen

ja ich dachte mir schon, das ich die XNA Komponente nicht einfach hätte rausnehmen sollen 😄 aber es ist ja noch alles im repo, also halb so wild :D ich bin mit der doku schon ein gutes stück durch, aber ncoh nciht ganz, aktuell machen mir die Variablen Kopfschmerzen aber das ist etwas für das nächste mal :D

**Comment by tomwendel** [comment]
Weiterhin nicht sicher mit dem Framework. Solange wir keine awesome Lösung für Windows 7 haben und auch keine unserer Komponenten dringend was höheres als 4.0 braucht, würde ich vorerst dabei bleiben.

**Comment by tomwendel** [comment]
Eine kleine Sache ist hier noch übrig: Das WiX Setup muss noch die Version aus GitVersion übernehmen

**Comment by TheBlubb14** [comment]
Der Installer und die Lizenz sollten auch auf Deutsch verfügbar sein
