### ISSUE TITLE
How to start on a modern Windows 10 with VS 2022

### ISSUE THREAD

**Issue by TFTomSun** [AntMeNet/AntMeClassic#55]
I recently tried to run AntMe.
I am able to create a project template. The project gets upgraded to .NET 4.8. When I start the simulation, I don't see any ants running. I assume its because of the .net 4.8 upgrade.  When I try to install the .NET 4.0 standalone installer, windows tells me that I don't need to install it, because there's a newer runtime already part of the OS.

**Comment by tomwendel** [comment]
Hi TFTomSun,

is it possible that we do not talk about the .NET Framework 4.0 but the XNA Framework 4.0? This one is required to render the 3D-Environment (at least in older versions). Can you please try out the current release from GitHub (https://github.com/AntMeNet/AntMeClassic/releases/tag/v1.7.4) to see if it is fixed here? Newer versions make use of FNA, which is a proper replacement of the XNA Framework without all that dependencies.

**Comment by TFTomSun** [comment]
Hi Tom,
I found the solution already. By default non of the rendering plugins were active - and therefore the simulation started without showing anything. So it works after the migration of the template project to .NET4.8 + XNA Framework + activating one of the renderings. Thanks for your support.
